version: '3.3'
services:

  db:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    env_file:
      - .env

  backend:
    build: .
    restart: always
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - .env

volumes:
  static_volume:
  media_volume:
  postgres_volume:
