# Generated by Django 4.2.3 on 2023-07-18 09:30

import clients.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Адрес', 'verbose_name_plural': 'Адреса'},
        ),
        migrations.AlterModelOptions(
            name='communication',
            options={'verbose_name': 'Средство связи', 'verbose_name_plural': 'Средства связи'},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'Документ', 'verbose_name_plural': 'Документы'},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'verbose_name': 'Работа', 'verbose_name_plural': 'Работы'},
        ),
        migrations.AlterField(
            model_name='address',
            name='apartment',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер квартиры, офиса и т.д.'),
        ),
        migrations.AlterField(
            model_name='address',
            name='zipCode',
            field=models.CharField(max_length=6, validators=[clients.validators.zip_code_validator], verbose_name='Почтовый индекс'),
        ),
    ]
