# Generated by Django 4.2.3 on 2023-07-18 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_job_datedismissal_alter_job_dateemp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='factAddress',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.address', verbose_name='Фактический адрес'),
        ),
        migrations.AlterField(
            model_name='job',
            name='jurAddress',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_clients', to='clients.address', verbose_name='Юридический адрес'),
        ),
    ]
