# Generated by Django 4.2.3 on 2023-07-18 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_job_factaddress_alter_job_juraddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='children',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='parent',
                to='clients.child',
                verbose_name='Дети',
            ),
        ),
    ]
