# Generated by Django 4.2.3 on 2023-07-18 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_alter_client_children'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='children',
        ),
        migrations.RemoveField(
            model_name='client',
            name='communications',
        ),
        migrations.RemoveField(
            model_name='client',
            name='documentIds',
        ),
        migrations.RemoveField(
            model_name='client',
            name='jobs',
        ),
        migrations.AddField(
            model_name='client',
            name='children',
            field=models.ManyToManyField(blank=True, null=True, related_name='parent', to='clients.child', verbose_name='Дети'),
        ),
        migrations.AddField(
            model_name='client',
            name='communications',
            field=models.ManyToManyField(related_name='client', to='clients.communication'),
        ),
        migrations.AddField(
            model_name='client',
            name='documentIds',
            field=models.ManyToManyField(related_name='client', to='clients.document', verbose_name='Идентификаторы документов'),
        ),
        migrations.AddField(
            model_name='client',
            name='jobs',
            field=models.ManyToManyField(related_name='emploee', to='clients.job'),
        ),
    ]
