# Generated by Django 4.2.3 on 2023-07-19 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_alter_client_children_alter_client_communications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='typeEducation',
            field=models.CharField(choices=[('secondary', 'Среднее'), ('secondarySpecial', 'Среднее специальное'), ('incompleteHigher', 'Незаконченное высшее'), ('higher', 'Высшее'), ('twoOrMoreHigher', 'Два и более высших образований'), ('academicDegree', 'Академическая степень')], max_length=50, verbose_name='Тип образования'),
        ),
        migrations.AlterField(
            model_name='job',
            name='type',
            field=models.CharField(blank=True, choices=[('main', 'Основная работа'), ('part_time', 'Частичная занятость')], max_length=20, verbose_name='Тип работы'),
        ),
    ]
