# Generated by Django 4.2.3 on 2023-07-19 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_alter_child_dob_alter_child_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='livingAddress',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='living_person',
                to='clients.address',
            ),
        ),
        migrations.AlterField(
            model_name='client',
            name='passport',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='clients.passport',
            ),
        ),
        migrations.AlterField(
            model_name='client',
            name='regAddress',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='clients.address',
            ),
        ),
    ]
