# Generated by Django 4.2.3 on 2023-07-20 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0013_alter_client_communications_alter_client_documentids'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='spouse',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.client'),
        ),
    ]
