# Generated by Django 4.2.3 on 2023-07-20 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0015_remove_client_spouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='spouse',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.client', verbose_name='Супруг(а)'),
        ),
    ]
