# Generated by Django 4.2.3 on 2023-07-21 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0016_client_spouse'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='passport',
            unique_together={('series', 'number')},
        ),
    ]
