# Generated by Django 4.2.3 on 2023-07-21 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0018_alter_passport_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='jobs',
            field=models.ManyToManyField(blank=True, null=True, related_name='emploee', to='clients.job'),
        ),
    ]
