# Generated by Django 4.2.3 on 2023-07-21 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0019_alter_client_jobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='День рождения'),
        ),
        migrations.AlterField(
            model_name='client',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='День рождения'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='dateIssued',
            field=models.DateField(verbose_name='Дата выдачи'),
        ),
    ]
