# Generated by Django 4.2.3 on 2023-07-21 10:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0020_alter_child_dob_alter_client_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='dob',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='День рождения'),
        ),
        migrations.AlterField(
            model_name='client',
            name='dob',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='День рождения'),
        ),
        migrations.AlterField(
            model_name='client',
            name='jobs',
            field=models.ManyToManyField(blank=True, related_name='emploee', to='clients.job'),
        ),
        migrations.AlterField(
            model_name='job',
            name='dateDismissal',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Дата увольнения'),
        ),
        migrations.AlterField(
            model_name='job',
            name='dateEmp',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Дата трудоустройства'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='dateIssued',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата выдачи'),
        ),
    ]
