# Generated by Django 4.2.3 on 2023-07-22 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0021_alter_child_dob_alter_client_dob_alter_client_jobs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='livingAddress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='living_person', to='clients.address'),
        ),
        migrations.AlterField(
            model_name='client',
            name='regAddress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.address'),
        ),
    ]
