# Generated by Django 4.2.3 on 2023-07-22 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0022_alter_client_livingaddress_alter_client_regaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='passport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.passport'),
        ),
        migrations.AlterField(
            model_name='client',
            name='regAddress',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.address'),
        ),
    ]
