# Generated by Django 4.2.3 on 2023-07-22 15:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0024_alter_client_passport_alter_client_regaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='dob',
            field=models.DateTimeField(blank=True, default=datetime.date.today, null=True, verbose_name='День рождения'),
        ),
        migrations.AlterField(
            model_name='client',
            name='dob',
            field=models.DateTimeField(blank=True, default=datetime.date.today, null=True, verbose_name='День рождения'),
        ),
        migrations.AlterField(
            model_name='job',
            name='dateDismissal',
            field=models.DateTimeField(blank=True, default=datetime.date.today, null=True, verbose_name='Дата увольнения'),
        ),
        migrations.AlterField(
            model_name='job',
            name='dateEmp',
            field=models.DateTimeField(blank=True, default=datetime.date.today, null=True, verbose_name='Дата трудоустройства'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='dateIssued',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='Дата выдачи'),
        ),
    ]
